version: '3.9'

services:
  app:
    build: .
    volumes: 
      - ./app:/romano_web_api/app
    ports: 
      - 5000:5000
    environment: 
      PORT: 5000
      FLASK_ENV: development
      PYTHONPATH: /romano_web_api/app
